name: Auto Assign Author

on:
  pull_request_target:
    types: [ opened, reopened ]

permissions:
  pull-requests: write

jobs:
  assign-author:
    name: Assign PR Author
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.0