name: Build - Bump Version Number

on:
  workflow_dispatch:
      
env:
  version_file: "Version.xcconfig"

jobs:
  BumpAndTag:
    name: Bump Build, Create Tag
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Import GPG Key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.ORG_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.ORG_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
        
        
      - name: Find version, build number and update
        run: |
          # Find build number and increment
          CURRENT_PROJECT_VERSION=$(grep -w "CURRENT_PROJECT_VERSION" "${{ env.version_file }}" | cut -d'=' -f2 | tr -d ' ')
          ((CURRENT_PROJECT_VERSION+=1))
          sed -i "s/\(CURRENT_PROJECT_VERSION *= *\).*/\1$CURRENT_PROJECT_VERSION/" "${{ env.version_file }}"

          # Find version number
          MARKETING_VERSION=$(grep -w "MARKETING_VERSION" "${{ env.version_file }}" | cut -d'=' -f2 | tr -d ' ')

          # Create new full version number
          NEW_TAG="v$MARKETING_VERSION+$CURRENT_PROJECT_VERSION"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$CURRENT_PROJECT_VERSION" >> $GITHUB_ENV
          
      - name: Commit build number
        run: |
          git add "${{ env.version_file }}"
          git commit -S -m "bump: Build Number to: ${{ env.NEW_TAG }} [skip ci]" || echo "No changes to commit"
          git push
        env:
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
          
      - name: Create tag
        run: |
          git tag -s ${{ env.NEW_TAG }} -m "${{ env.NEW_TAG }}"
          git push origin ${{ env.NEW_TAG }}
        env:
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
          
    outputs:
      NEW_TAG: ${{ env.NEW_TAG }}
      BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
          
  CreateChangelogAndRelease:
    needs: BumpAndTag
    uses: ./.github/workflows/build-create-release.yml
    secrets: inherit
    with:
      tag_name: ${{ needs.BumpAndTag.outputs.NEW_TAG }}
      build_number: ${{ needs.BumpAndTag.outputs.BUILD_NUMBER }}