name: Update Changelog, Create Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      build_number:
        required: true
        type: string

jobs:
  changelog:
    name: Update Changelog, Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          fetch-depth: 0
          
      - name: Import GPG Key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.ORG_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.ORG_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          
      - name: Pull again (workflow uses triggered commit as base)
        run: |
          git pull
 
      - name: Update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1.7.0
        with:
          tag: ${{ inputs.tag_name }}
          excludeTypes: ""
          includeInvalidCommits: true
          token: ${{ github.token }}
 
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}
          draft: false
          name: ${{ inputs.tag_name }}
          body: ${{ steps.changelog.outputs.changes }}
          
      - name: Whats new
        run: |
          echo "${{ steps.changelog.outputs.changes }}"
 
      - name: Commit CHANGELOG.md
        run: |
          git pull
          git add "CHANGELOG.md"
          git commit -S -m "docs: update CHANGELOG.md for ${{ inputs.tag_name }} [skip ci]" || echo "No changes to commit"
          git push
        env:
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
  