name: Build Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCS: "docs"
  DOCUGEN: "DocBuilder"
  DOCSOURCE: "DocBuilder/source"
  TEMPLATES: "DocBuilder/templates"
  DOCSCRIPTS: "DocBuilder/scripts"
  GIT_EMAIL: "test@github.com"
  GIT_NAME: "DocBot"

jobs:

  checkWords:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Check disallowed words
        run: |
          python ${{ env.DOCSCRIPTS }}/checkDisallowedWords.py -src "${{ env.DOCSOURCE }}/"
    

  buildMarkdown:
    runs-on: macos-latest 
    needs: checkWords
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
          
      - name: Build Markdown Documentation
        run: |
          rm -rf ${{ env.DOCS }}/Markdown/*.md
          python ${{ env.DOCSCRIPTS }}/buildMarkdownDocumentation.py -t "${{ env.TEMPLATES }}/template.md" -src "${{ env.DOCSOURCE }}/" -dst "${{ env.DOCS }}/Markdown"
          cp -a ${{ env.DOCSOURCE }}/media ${{ env.DOCS }}/Markdown
          
      - name: Commit files
        run: |
          git config --local user.email ${{ env.GIT_EMAIL }}
          git config --local user.name ${{ env.GIT_NAME }}
          git pull
          git add ${{ env.DOCS }}/Markdown/.
          git commit -m "Update markdown files" || echo "No changes to commit"
          git push

  buildAppleHelpBook:
    runs-on: macos-latest
    needs: buildMarkdown
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
          
      - name: Build Markdown Documentation
        run: |
          rm -rf ${{ env.DOCUGEN }}/AppleHelpBook/Contents/Resources/Base.lproj/*.html
          python ${{ env.DOCSCRIPTS }}/buildAppleHelpBook.py -t "${{ env.TEMPLATES }}/templateAppleHelpBook.html" -src "${{ env.DOCSOURCE }}/" -dst "${{ env.DOCUGEN }}/AppleHelpBook/Contents/Resources/Base.lproj"
          
      - name: Generate Search Indexes
        run: |
          echo "Change directory"
          cd ${{ env.DOCUGEN }}/AppleHelpBook/Contents/Resources/Base.lproj
          
          echo "Start advanced index generation"
          hiutil -I corespotlight -Caf Base.lproj.cshelpindex -vv .
          hiutil -I lsm  -Caf Base.lproj.helpindex -vv .
          echo "Finish advanced index generation"

          # hiutil -V (version is hiutil version 2.0 (66))

          echo "examine .helpindex"
          hiutil -I corespotlight -Af Base.lproj.helpindex
          
          echo "examine .cshelpindex"
          hiutil -I corespotlight -Af Base.lproj.cshelpindex
          
      - name: Copy Media
        run: |
          rm -rf ${{ env.DOCUGEN }}/AppleHelpBook/Contents/Resources/Base.lproj/media
          cp -a ${{ env.DOCSOURCE }}/media ${{ env.DOCUGEN }}/AppleHelpBook/Contents/Resources/Base.lproj/media

      - name: Commit files
        run: |
          git config --local user.email ${{ env.GIT_EMAIL }}
          git config --local user.name ${{ env.GIT_NAME }}
          git pull
          git add ${{ env.DOCUGEN }}/AppleHelpBook/.
          git status
          git commit -m "Update Apple HelpBook files" || echo "No changes to commit"
          git push
          
  buildDocumentationSitemap:
    runs-on: macos-latest
    needs: checkWords
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
          
      - name: Build Markdown Documentation
        run: |
          python ${{ env.DOCSCRIPTS }}/buildDocumentationSitemap.py -t "${{ env.TEMPLATES }}/templateSitemap.xml" -src "${{ env.DOCSOURCE }}/" -dst "${{ env.DOCS }}"
          
      - name: Commit files
        run: |
          git config --local user.email ${{ env.GIT_EMAIL }}
          git config --local user.name ${{ env.GIT_NAME }}
          git pull
          git add ${{ env.DOCS }}/sitemap.xml
          git status
          git commit -m "Update Documentation Sitemap file" || echo "No changes to commit"
          git push

  buildGitHubDocs:
    runs-on: macos-latest
    needs: buildAppleHelpBook
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
          
      - name: Build GitHub Documentation
        run: |
          rm -rf docs/*.html
          python ${{ env.DOCSCRIPTS }}/buildGitHubDocs.py -t "${{ env.TEMPLATES }}/templateGitHubDocs.html" -src "${{ env.DOCSOURCE }}/" -dst "${{ env.DOCS }}/html"
          cp -a ${{ env.DOCSOURCE }}/media ${{ env.DOCS }}/html
          cp -a ${{ env.DOCSOURCE }}/css ${{ env.DOCS }}/html
          
      - name: Commit files
        run: |
          git config --local user.email ${{ env.GIT_EMAIL }}
          git config --local user.name ${{ env.GIT_NAME }}
          git pull
          git add ${{ env.DOCS }}/html/.
          git commit -m "Update GitHub Doc files" || echo "No changes to commit"
          git push